basePath: /
definitions:
  dto.DashboardDTO:
    properties:
      stats:
        $ref: '#/definitions/dto.StatsDTO'
      username:
        type: string
    type: object
  dto.FavoriteResponse:
    properties:
      id:
        type: string
      user_id:
        type: string
    type: object
  dto.IngredientResponse:
    properties:
      amount:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  dto.RecipeResponse:
    properties:
      category:
        type: string
      cook_time:
        type: integer
      description:
        type: string
      favorites:
        items:
          $ref: '#/definitions/dto.FavoriteResponse'
        type: array
      id:
        type: string
      ingredients:
        items:
          $ref: '#/definitions/dto.IngredientResponse'
        type: array
      prep_time:
        type: integer
      servings:
        type: integer
      steps:
        items:
          $ref: '#/definitions/dto.StepResponse'
        type: array
      thumbnail:
        type: string
      title:
        type: string
      user:
        $ref: '#/definitions/dto.UserSummaryResponse'
    type: object
  dto.StatsDTO:
    properties:
      numberOfFavorites:
        type: integer
      numberOfRecipes:
        type: integer
    type: object
  dto.StepResponse:
    properties:
      detail:
        type: string
      id:
        type: string
      number:
        type: integer
    type: object
  dto.UserSummaryResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Favorite:
    properties:
      id:
        type: string
      recipe:
        $ref: '#/definitions/models.Recipe'
      recipe_id:
        type: string
      user_id:
        type: string
    type: object
  models.Ingredient:
    properties:
      amount:
        type: string
      id:
        type: string
      name:
        type: string
      recipe_id:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      data:
        $ref: '#/definitions/models.UserResponse'
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  models.Recipe:
    properties:
      category:
        type: string
      cook_time:
        type: integer
      created_at:
        type: string
      description:
        type: string
      favorites:
        items:
          $ref: '#/definitions/models.Favorite'
        type: array
      id:
        type: string
      ingredients:
        items:
          $ref: '#/definitions/models.Ingredient'
        type: array
      prep_time:
        type: integer
      servings:
        type: integer
      steps:
        items:
          $ref: '#/definitions/models.Step'
        type: array
      thumbnail:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/models.User'
        description: Relations
      user_id:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.RegisterResponse:
    properties:
      data:
        $ref: '#/definitions/models.UserResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  models.ResponseError:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  models.Step:
    properties:
      detail:
        type: string
      id:
        type: string
      number:
        type: integer
      recipe_id:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      favorites:
        items:
          $ref: '#/definitions/models.Favorite'
        type: array
      id:
        type: string
      name:
        type: string
      recipes:
        items:
          $ref: '#/definitions/models.Recipe'
        type: array
      updated_at:
        type: string
    type: object
  models.UserResponse:
    properties:
      email:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
host: http://192.168.100.247:8080
info:
  contact: {}
  description: API documentation for recipe API
  title: Recipe API
  version: "1.0"
paths:
  /api/myrecipes:
    get:
      description: Get all recipes created by the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.RecipeResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get my recipes
      tags:
      - Recipes
  /api/page/dashboard:
    get:
      description: Get user dashboard information including total recipes and favorites
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DashboardDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user dashboard data
      tags:
      - Dashboard
  /api/recipes:
    get:
      description: Retrieve all available recipes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.RecipeResponse'
            type: array
      summary: Get all recipes for all users
      tags:
      - Recipes
    post:
      consumes:
      - multipart/form-data
      - multipart/form-data
      description: |-
        Create a new recipe with title, description, category, prep_time, cook_time, ingredients, steps, and thumbnail
        Create a new recipe with title, description, category, prep_time, cook_time, ingredients, steps, and thumbnail
      parameters:
      - description: Thumbnail Image
        in: formData
        name: thumbnail
        type: file
      - description: Recipe Title
        in: formData
        name: title
        required: true
        type: string
      - description: Recipe Description
        in: formData
        name: description
        type: string
      - description: Recipe Category
        in: formData
        name: category
        type: string
      - description: Preparation Time
        in: formData
        name: prep_time
        type: integer
      - description: Cooking Time
        in: formData
        name: cook_time
        type: integer
      - description: Number of Servings
        in: formData
        name: servings
        type: integer
      - description: Ingredients JSON Array
        in: formData
        name: ingredients
        type: string
      - description: Steps JSON Array
        in: formData
        name: steps
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RecipeResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new recipe by the authenticated user
      tags:
      - Recipes
      - Recipes
  /api/recipes/{id}:
    delete:
      description: Delete a recipe by ID
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete recipe
      tags:
      - Recipes
    get:
      description: Retrieve a recipe by its ID
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RecipeResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get recipe by ID
      tags:
      - Recipes
    put:
      consumes:
      - multipart/form-data
      - multipart/form-data
      description: Update recipe details by ID
      parameters:
      - description: New Thumbnail Image
        in: formData
        name: thumbnail
        type: file
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      - description: Recipe Title
        in: formData
        name: title
        type: string
      - description: Recipe Description
        in: formData
        name: description
        type: string
      - description: Recipe Category
        in: formData
        name: category
        type: string
      - description: Preparation Time
        in: formData
        name: prep_time
        type: integer
      - description: Cooking Time
        in: formData
        name: cook_time
        type: integer
      - description: Number of Servings
        in: formData
        name: servings
        type: integer
      - description: Ingredients JSON Array
        in: formData
        name: ingredients
        type: string
      - description: Steps JSON Array
        in: formData
        name: steps
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RecipeResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update recipe
      tags:
      - Recipes
      - Recipes
  /api/recipes/{recipe_id}/favorites:
    post:
      description: |-
        This endpoint will add the recipe to user's favorites if it is not already favorited.
        If the recipe is already in favorites, it will remove it instead.
      parameters:
      - description: Recipe ID
        in: path
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'message: ''Added to favorites'' or ''Removed from favorites'''
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid recipe ID
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: post recipe favorite
      tags:
      - Favorites
  /api/recipes/favorites:
    get:
      consumes:
      - application/json
      description: Get all favorite recipes of the logged-in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Favorite'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all favorite recipes by user
      tags:
      - Favorites
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Login user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Register user
      tags:
      - Auth
  /logout:
    post:
      consumes:
      - application/json
      description: Blacklist token from Authorization header
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  message:
                    type: string
                type: object
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  error:
                    type: string
                type: object
            type: object
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
